apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: fraudnet/terraform-aws-dynamodb
    sentry.io/project-slug: fraudnet/terraform-aws-dynamodb
  name: terraform-aws-dynamodb
spec:
  dependsOn: []
  lifecycle: production
  owner: DevOps
  type: service
